SimpleInjectorMVC/Models/ErrorViewModel.cs
using System;

namespace SimpleInjectorMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimpleInjectorMVC/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SimpleInjectorMVC.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index(string e)
        {
            ViewData["error"] = e;
            return View();
        }
    }
}

SimpleInjectorMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimpleInjectorMVC.Models;

namespace SimpleInjectorMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SimpleInjectorMVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Contract.Interfaces;
using Microsoft.AspNetCore.Mvc;
using SimpleInjectorMVC.Models;
using TVDMS.Common.Commands;
using BLL.Contract.Models.Order;
using BLL.Contract.Commands.OrderCommands;
using TVDMS.Common.Queries;
using BLL.Contract.Queries.OrderQueries;
using TVDMS.Common.DI;

namespace SimpleInjectorMVC.Controllers
{
    public class OrderController : Controller
    {
        private ICommandBus commandBus;
        private IQueryProcessor queryProcessor;
        public OrderController(ICommandBus commandBus, IQueryProcessor queryProcessor)
        {
            this.commandBus = commandBus;
            this.queryProcessor = queryProcessor;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateOrder()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateOrder(CreateOrder createOrder)
        {
            var createOrderCommand = new CreateOrderCommand();
            createOrder.Datetime = DateTime.Now;
            createOrderCommand.CreateOrder = createOrder;
            commandBus.Submit(createOrderCommand);
            return RedirectToAction("ViewOrder");
        }
        [HttpGet]
        public IActionResult ViewOrder(FilterOrder filterOrder, SortOrder sortOrder)
        {
            var viewOrderQuery = new ViewOrderQuery(filterOrder, sortOrder);
            var viewOrderList = queryProcessor.Process(viewOrderQuery);
            return View(viewOrderList);
        }
        public IActionResult ErrorOrder()
        {
            throw new Exception("error order");
        }
    }
}

SimpleInjectorMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Contract.Commands.UserCommands;
using BLL.Contract.Models.User;
using BLL.Contract.Queries.UserQueries;
using Microsoft.AspNetCore.Mvc;
using TVDMS.Common.Commands;
using TVDMS.Common.Queries;

namespace SimpleInjectorMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly ICommandBus commandBus;
        private readonly IQueryProcessor queryProcessor;
        public UserController(ICommandBus commandBus, IQueryProcessor queryProcessor)
        {
            this.commandBus = commandBus;
            this.queryProcessor = queryProcessor;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult LoginUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LoginUser(LoginUser loginUser)
        {
            var loginUserSingleQuery = new LoginUserSingleQuery(loginUser);
            queryProcessor.ProcessSingleQuery(loginUserSingleQuery);
            ViewData["Login"] = "Login Success";
            return View();
        }
        [HttpGet]
        public IActionResult RegisterUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RegisterUser(RegisterUser registerUser)
        {
            registerUser.Datetime = DateTime.Now;
            var registerUserCommand = new RegisterUserCommand(registerUser);
            commandBus.Submit(registerUserCommand);
            return RedirectToAction("LoginUser");
        }
    }
}

SimpleInjectorMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SimpleInjectorMVC/Views/Order/CreateOrder.cshtml
@{
    ViewData["Title"] = "CreateOrder";
}

<h1>Create a Order</h1>

<hr>

<h2>Order Form</h2>

<form asp-controller="Order" asp-action="CreateOrder" method="post" id="CreateOrderForm">
    <div class="form-group">
        <label for="CreateOrderName">Name</label>
        <input type="text" class="form-control" id="CreateOrderName" name="Name" placeholder="Enter your name">
        <small id="nameHelp" class="form-text text-muted">Put down your name so we know who you are</small>
    </div>
    <div class="form-group">
        <label for="CreateOrderFood">Food</label>
        <input type="text" class="form-control" id="CreateOrderFood" name="Food" placeholder="YOUR FOOD ORDER">
    </div>
    <div class="form-group">
        <label for="CreateOrderPrice">Price</label>
        <input type="number" class="form-control" id="CreateOrderPrice" name="Price" placeholder="State your expected price">
    </div>
    <button type="submit" class="btn btn-outline-danger" id="CreateOrderBtn">Submit</button>
    @if (ViewData["error"] != null)
    {
        <small id="createOrderError" class="form-text text-danger">Error: @ViewData["error"]</small>
    }
    <small id="createOrderErrorJS" class="form-text text-danger"></small>
</form>

<hr>

<a href="/Order">Back to Order Page</a>

@section scripts {
    <script src="~/js/Order/CreateOrder.js"></script>
}

SimpleInjectorMVC/Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Order";
}

<h1>Order here</h1>

<a href="/Order/CreateOrder">Create Order</a>
<hr>
<a href="/Order/ViewOrder">View Order</a>

SimpleInjectorMVC/Views/Order/ViewOrder.cshtml
@using BLL.Contract.Models.Order;

@model List<ViewOrder>

@{
    ViewData["Title"] = "ViewOrder";
}



<h1>View the Orders</h1>

@if (Model == null)
{
    <p>no data in db</p>
}
else
{
    <table class="table" id="ViewOrderTable">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Food</th>
                <th scope="col">Price</th>
                <th scope="col">Date and Time</th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th scope="col" id="sortName">
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="ascending" asp-route-SortColumn="Name">asc</a>
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="descending" asp-route-SortColumn="Name">des</a>
                </th>
                <th scope="col" id="sortFood">
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="ascending" asp-route-SortColumn="Food">asc</a>
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="descending" asp-route-SortColumn="Food">des</a>
                </th>
                <th scope="col" id="sortPrice">
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="ascending" asp-route-SortColumn="Price">asc</a>
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="descending" asp-route-SortColumn="Price">des</a>
                </th>
                <th scope="col" id="sortDatetime">
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="ascending" asp-route-SortColumn="Datetime">asc</a>
                    <a asp-controller="Order" asp-action="ViewOrder" asp-route-SortMethod="descending" asp-route-SortColumn="Datetime">des</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var data in Model)
            {
                <tr accesskey=@data.Id>
                    <td name="Name">@data.Name</td>
                    <td name="Food">@data.Food</td>
                    <td name="Price">@data.Price</td>
                    <td name="Datetime">@data.Datetime</td>
                </tr>
            }
        </tbody>
    </table>

    <hr>

    <h2>Filter Orders</h2>

    <form asp-controller="Order" asp-action="ViewOrder" method="get">
        <div class="form-group">
            <label for="NameLength">Length of Name longer than</label>
            <input type="number" class="form-control" id="NameLength" name="NameLength">
        </div>
        <div class="form-group">
            <label for="FoodLength">Length of Food longer than</label>
            <input type="number" class="form-control" id="FoodLength" name="FoodLength">
        </div>
        <div class="form-group">
            <label for="PriceRange">Price Higher than</label>
            <input type="number" class="form-control" id="PriceRange" name="PriceRange">
        </div>
        <button type="submit" class="btn btn-outline-danger" id="CreateOrderBtn">Submit</button>
    </form>
}

<a href="/Order">Back to Order Page</a>

<h1>@ViewData["test"]</h1>

@section  scripts {
    <script src="~/js/Order/ViewOrder.js"></script>
}

SimpleInjectorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleInjectorMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleInjectorMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SimpleInjectorMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SimpleInjectorMVC/Views/User/Index.cshtml
@{
    ViewData["Title"] = "User Page";
}

<h1>Login or Register</h1>

<a asp-controller="User" asp-action="LoginUser">Login</a>
<hr>
<a asp-controller="User" asp-action="RegisterUser">Register</a>

SimpleInjectorMVC/Views/User/LoginUser.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>User Login</h1>

<form asp-controller="User" asp-action="LoginUser" method="post" id="LoginUserForm">
    <div class="form-group">
        <label for="LoginUserUsername">Username</label>
        <input type="text" class="form-control" id="LoginUserUsername" name="Username" placeholder="Enter your username">
    </div>
    <div class="form-group">
        <label for="LoginUserEmail">Email</label>
        <input type="email" class="form-control" id="LoginUserEmail" name="Email" placeholder="e.g. example@simpleInjection.com">
    </div>
    <div class="form-group">
        <label for="LoginUserPassword">Password</label>
        <input type="password" class="form-control" id="LoginUserPassword" name="Password">
    </div>
    <button type="submit" class="btn btn-outline-primary" id="LoginUserBtn">Submit</button>
    @if (ViewData["Login"] != null)
    {
        <small id="LoginUserStatus" class="form-text text-danger">Status: @ViewData["Login"]</small>
    }
    <small id="LoginUserStatusJS" class="form-text text-danger"></small>
</form>

<hr>

<a href="/User">Back to User Page</a>

@section scripts {
    <script src="~/js/User/LoginUser.js"></script>
}

SimpleInjectorMVC/Views/User/RegisterUser.cshtml
@{
    ViewData["Title"] = "RegisterUser";
}

<h1>New User Register</h1>

<hr>

<h2>Register Form</h2>

<form asp-controller="User" asp-action="RegisterUser" method="post" id="RegisterUserForm">
    <div class="form-group">
        <label for="RegisterUserUsername">Username</label>
        <input type="text" class="form-control" id="RegisterUserUsername" name="Username" placeholder="Enter your username">
    </div>
    <div class="form-group">
        <label for="RegisterUserEmail">Email</label>
        <input type="email" class="form-control" id="RegisterUserEmail" name="Email" placeholder="e.g. example@simpleInjection.com">
    </div>
    <div class="form-group">
        <label for="RegisterUserPassword">Password</label>
        <input type="password" class="form-control" id="RegisterUserPassword" name="Password">
    </div>
    <div class="form-group">
        <label for="RegisterUserConfirmPassword">Confirm Password</label>
        <input type="password" class="form-control" id="RegisterUserConfirmPassword" name="ConfirmPassword">
    </div>
    <button type="submit" class="btn btn-outline-primary" id="RegisterUserBtn">Submit</button>
    @if (ViewData["error"] != null)
    {
        <small id="RegisterUserError" class="form-text text-danger">Error: @ViewData["error"]</small>
    }
    <small id="RegisterUserErrorJS" class="form-text text-danger"></small>
</form>

<hr>

<a href="/User">Back to User Page</a>

@section scripts {
    <script src="~/js/User/RegisterUser.js"></script>
}